### ISSUE TITLE
Checkpoint 1 is ready for review

### ISSUE THREAD

**Issue by johnoliver42** [johnoliver42/invoice-maker#1]
@pawaitemadisoncollege - checkpoint 1 is ready for review

**Comment by pawaitemadisoncollege** [comment]
Things are looking very good here John. Your planning is solid through weeks 6-7, with a good level of detail about the user and role.  I think there are some tasks missing such as the controllers and details for the invoice and shipping labels beyond the jsp. 

- [ ] Will users be able to update or delete anything as part of the MVP user stories?  Full CRUD is part of the project requirements, so I'm hoping you'd be able to add something in to the MVP stories to include update/delete, as create and read seem to be well-covered.

**Comment by johnoliver42** [comment]
I will be using EasyPost for the shipping API.

I have updated the user stories to add editing and deleting of invoices.
