### ISSUE TITLE
Week 2 - Instructor feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [johnoliver42/invoice-maker#1]
@johnoliver42 Just so it doesn't fall off the radar for week 2 deliverables:

Both of the following appear empty when I view them in GitHub: 
- [x] Add a README.md and begin documenting your project problem statement/goal.
- [x] Add a timeLog.md and then enter your time log entries from Week 1 and 2. If you prefer, you may choose to write journal entries to document your progress, problems solved, key learning points, and anything else you find useful to track. You should track all time spent on Ent Java work outside of class, not just indie project work.

**Comment by johnoliver42** [comment]
Both of these issues have been resolved. Albeit a bit late.
